import { Cep } from "@/types/Cep";

export const limoeiroStreets: Cep[] = [
  {
    cep: "62936-490",
    logradouro: "Travessa Joao Menezes de Oliveira",
    bairro: "Antonio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-442",
    logradouro: "Manoel Fidelis Maia até 99999 lado impar av",
    bairro: "Antonio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-440",
    logradouro: "Manoel Fidelis Maia de 2 ao fim lado par av",
    bairro: "Antonio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-526",
    logradouro: "Higino Lourengo da Silva",
    bairro: "Antonio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-448",
    logradouro: "João Ferreira Freitas",
    bairro: "Antonio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-456",
    logradouro: "José Lopes de Andrade",
    bairro: "Antonio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-506",
    logradouro: "José Nunes Guerreiro Sobrinho",
    bairro: "Antonio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-566",
    logradouro: "Luiz Fortunato de Andrade",
    bairro: "Antonio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-474",
    logradouro: "Maria Carmélia Maia de Andrade",
    bairro: "Antonio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-534",
    logradouro: "Raimunda Amélia de Oliveira",
    bairro: "Antonio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-482",
    logradouro: "Regina Ferreira de Araujo",
    bairro: "Antonio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-580",
    logradouro: "Presidente Epitácio Pessoa lado par",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-540",
    logradouro: "Rua Deputado Expedito Maia da Costa",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-544",
    logradouro: "Rua Auditora Fernanda Ney",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-576",
    logradouro: "Travessa Fortunato de Andrade",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-578",
    logradouro: "Travessa Fortunato de Andrade I",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-546",
    logradouro: "Francisco de Holanda Martins",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-518",
    logradouro: "Hipólito Nepomuceno de Andrade",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-444",
    logradouro: "Isaura Nunes Malveira",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-584",
    logradouro: "João Batista Gomes",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-552",
    logradouro: "Travessa João Bento Filho",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-502",
    logradouro: "Joao Conrado Guimaraes",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-514",
    logradouro: "Travessa João Felicio Costa",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-524",
    logradouro: "João Pantaledo de Moura",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-530",
    logradouro: "Deputado Joaquim Bento de Sousa Andrade",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-488",
    logradouro: "José Amancio de Moura",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-550",
    logradouro: "José Bento Filho",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-480",
    logradouro: "Travessa José Evandro Soares da Silva",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-538",
    logradouro: "Secretário José Gildo Craveiro Holanda",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-454",
    logradouro: "José Gonçalves Guerreiro",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-466",
    logradouro: "José Malveira Maia",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-572",
    logradouro: "José Victor de Oliveira",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-574",
    logradouro: "José Victor de Oliveira I",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-472",
    logradouro: "Luiz Paulino Gomes",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-588",
    logradouro: "Travessa Manoel Fernandes de Sousa",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-500",
    logradouro: "Maria José Chaves de Almeida",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-486",
    logradouro: "Maria José Sousa de Freitas",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-476",
    logradouro: "Mariana Faganha Gadelha",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-522",
    logradouro: "Travessa Pantaledo de Moura",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-492",
    logradouro: "Pedro Batista de Oliveira",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-460",
    logradouro: "Raimundo Malveira Maia",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-510",
    logradouro: "Raimundo Tomas de Aquino",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-556",
    logradouro: "Travessa Rogerlando Saraiva Rabelo",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-494",
    logradouro: "Rosa Teresa de Jesus",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-532",
    logradouro: "Travessa Rosa Teresa de Jesus",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-484",
    logradouro: "São Sebastião",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-470",
    logradouro: "Valdeci Ferreira de Araujo",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-586",
    logradouro: "Valdemiro Ferreira de Matos",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-542",
    logradouro: "Vereador Valderilo Holanda de Oliveira",
    bairro: "Antônio Holanda",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-388",
    logradouro: "Cornélio Alves de Freitas",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-306",
    logradouro: "Travessa Estevao Remigio de Freitas",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-302",
    logradouro: "Estevao Remigio de Freitas de 2451/2452 ao fim",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-384",
    logradouro: "Felipe Alves de Freitas",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-270",
    logradouro: "Francisco Nunes Guerreiro até 2175 lado impar",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-286",
    logradouro: "Deputado Franklin Gondim Chaves",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-382",
    logradouro: "Vila Holanda",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-320",
    logradouro: "Travessa Joao Lopes de Assis",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-318",
    logradouro: "João Lopes de Assis",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-324",
    logradouro: "Travessa Joao Lopes de Assis I",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-272",
    logradouro: "Joaquim Evaristo Gadelha de 3441/3442 ao fim",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-406",
    logradouro: "José Brito Junior",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-416",
    logradouro: "Travessa José Brito Junior",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-414",
    logradouro: "Travessa José Brito Junior I",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-412",
    logradouro: "Travessa José Brito Junior Il",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-410",
    logradouro: "Travessa José Brito Junior III",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-408",
    logradouro: "Travessa José Brito Junior IV",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-376",
    logradouro: "José de Castro Maia de Freitas de 546/547 ao fim",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-380",
    logradouro: "José Ednir Maia",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-326",
    logradouro: "José Ferreira Sombra até 1999/2000",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-304",
    logradouro: "Travessa José Hamilton de Oliveira",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-308",
    logradouro: "José Hamilton de Oliveira de 643/644 ao fim",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-282",
    logradouro: "Leéncio Anibal da Silva",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-300",
    logradouro: "Lucia Baltazar Costa até 99998/99999",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-292",
    logradouro: "Luis Nunes Guerreiro",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-390",
    logradouro: "Manuel Luis de Freitas",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-396",
    logradouro: "Travessa Manuel Luis de Freitas I",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-402",
    logradouro: "Travessa Manuel Luis de Freitas II",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-394",
    logradouro: "Travessa Manuel Luis de Freitas III",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-392",
    logradouro: "Travessa Manuel Luis de Freitas IV",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-404",
    logradouro: "Travessa Manuel Luis de Freitas V",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-400",
    logradouro: "Travessa Manuel Luis de Freitas 03",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-398",
    logradouro: "Travessa Manuel Luis de Freitas 04",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-280",
    logradouro: "Maria Assunção de Freitas",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-372",
    logradouro: "Marina Mendes de 1650/1651 ao fim",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-374",
    logradouro: "Travessa Marina Mendes VI",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-310",
    logradouro: "Cônego  Mizael Alves de Souza",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-322",
    logradouro: "Onésimo Remigio de Freitas",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-378",
    logradouro: "Travessa Onésimo Remigio de Freitas",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-274",
    logradouro: "Raimunda Lidia de Freitas Ferreira",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-296",
    logradouro: "Travessa Raimundo Mendes Guerreiro",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-294",
    logradouro: "Raimundo Mendes Guerreiro até 1117/1118",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-284",
    logradouro: "Raimundo Nonato de Moura",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-298",
    logradouro: "Valdemirio Holanda Nunes",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-370",
    logradouro: "Vital Alves de Freitas",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-386",
    logradouro: "Travessa Vital Alves de Freitas",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-524",
    logradouro: "Travessa Vital de Freitas I",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-526",
    logradouro: "Travessa Vital de Freitas II",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-528",
    logradouro: "Travessa Vital de Freitas Ill",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-278",
    logradouro: "José Lopes Maranhdo de 3452 a 4098 lado par",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-316",
    logradouro: "Sabino Roberto de Freitas de 3327 ao fim lado impar",
    bairro: "Boa Fé",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-232",
    logradouro: "Avenida Fidélis e Maia",
    bairro: "Bom Jesus",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-230",
    logradouro: "Francisco de Assis Andrade",
    bairro: "Bom Jesus",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-224",
    logradouro: "João Candido de Sousa",
    bairro: "Bom Jesus",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-670",
    logradouro: "Presidente Epitácio Pessoa lado impar",
    bairro: "Bom Jesus Cruzeiro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-684",
    logradouro: "Francisco Chagas Rabelo",
    bairro: "Bom Jesus Cruzeiro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-686",
    logradouro: "Juracy Chaves de Andrade",
    bairro: "Bom Jesus Cruzeiro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-680",
    logradouro: "Maria Augusta de Oliveira",
    bairro: "Bom Jesus Cruzeiro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-682",
    logradouro: "Travessa Maria Augusta de Oliveira",
    bairro: "Bom Jesus Cruzeiro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-676",
    logradouro: "Pedro Amorim de Oliveira",
    bairro: "Bom Jesus Cruzeiro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-678",
    logradouro: "Pedro Gomes Bezerra",
    bairro: "Bom Jesus Cruzeiro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-674",
    logradouro: "Professora Inés Augusta de Oliveira",
    bairro: "Bom Jesus Cruzeiro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-058",
    logradouro: "Francisco Holanda de Oliveira de 739/740 ao fim",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-152",
    logradouro: "Raimundo Mendes Guerreiro de 1119/1120 ao fim",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-102",
    logradouro: "Avenida do Contorno",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-124",
    logradouro: "Avenida Francisco Antônio de Lima",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-126",
    logradouro: "Rua Francisco Dantas Bandeira - Assis Bandeira",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-110",
    logradouro: "Francisco das Chagas Lucena",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-114",
    logradouro: "Francisco Gomes Maciel",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-142",
    logradouro: "Francisco Inacio da Silva Filho",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-052",
    logradouro: "Francisco Nunes Guerreiro de 2176/2177 ao fim",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-130",
    logradouro: "Franklin Chaves",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-146",
    logradouro: "Deputado Franklin Chaves",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-128",
    logradouro: "Franklin Gondim Chaves",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-044",
    logradouro: "Doutor Gaspar de Oliveira de 2357/2358 ao fim",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-148",
    logradouro: "Gaudéncio Ferreira de Freitas",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-132",
    logradouro: "Heldebrando Fernandes de Sousa",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-056",
    logradouro: "Travessa Joao Claudino dos Santos",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-096",
    logradouro: "João Roque Filho",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-150",
    logradouro: "Joaquim Evaristo Gadelha de 3801 ao fim lado impar ",
    bairro: "Bom nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-060",
    logradouro: "José Brito de Oliveira",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-062",
    logradouro: "Travessa José Felicio da Costa",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-090",
    logradouro: "José Felipe Sobrinho",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-122",
    logradouro: "José Gomes Neto",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-138",
    logradouro: "José Josino dos Anjos",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-040",
    logradouro: "José Lopes Maranhdo de 2951/2952 ao fim",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-094",
    logradouro: "Lauro Rebouças Filho até 1698/1699",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-050",
    logradouro: "Luis Sales Bandeira",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-064",
    logradouro: "Manfredo de Oliveira Lima de 985/986 ao fim",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-074",
    logradouro: "Manuel Cassimiro da Silva - Manoel Amara",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-046",
    logradouro: "Maria Assunção de Freitas",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-092",
    logradouro: "Maria do Carmo Amorim",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-082",
    logradouro: "Maria Irene Vidal",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-134",
    logradouro: "Maria Otilia Pereira",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-106",
    logradouro: "Maurina Holanda Cavalcante",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-054",
    logradouro: "Mixico Nonato",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-116",
    logradouro: "Olavio Rebougas de Oliveira",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-108",
    logradouro: "Pedro Olimpio de Souza",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-078",
    logradouro: "Vereador Raimundo Donato Chaves",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-070",
    logradouro: "Raimundo Felipe Neto de 1000/1001 ao fim",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-042",
    logradouro: "Raimundo Nonato de Moura",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-066",
    logradouro: "Raimundo Remigio de Freitas de 681/682 a 1799/1800",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-084",
    logradouro: "Tenente Sebastião",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-140",
    logradouro: "Vicente de Paula Freitas",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-088",
    logradouro: "Willian Bastos Franco",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-154",
    logradouro: "Lucia Baltazar Costa de 4450 ao fim lado par",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-098",
    logradouro: "Luis Gonzaga de Oliveira Osterne lado par",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-072",
    logradouro: "Manoel Saraiva de 871 ao fim lado impar",
    bairro: "Bom Nome",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-036",
    logradouro: "Cosme Damião da Silva até 3589 - lado impar",
    bairro: "Brotolandia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-018",
    logradouro: "Francisco Bandeira",
    bairro: "Brotolandia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-020",
    logradouro: "Engenheira Gerlêni de Castro",
    bairro: "Brotolandia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-000",
    logradouro: "João Maria de Freitas lado impar",
    bairro: "Brotolandia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-026",
    logradouro: "José Joaquim Filho",
    bairro: "Brotolandia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-010",
    logradouro: "José Osterne Juniode 850/851 ao fim",
    bairro: "Brotolandia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-028",
    logradouro: "Limério Osterne de 1300/1301 a 1598/1599",
    bairro: "Brotolandia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-034",
    logradouro: "Nair Holanda Maia",
    bairro: "Brotolandia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-008",
    logradouro: "Travessa Raimundo Fidélis de 1650/1651 ao fim",
    bairro: "Brotolandia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-014",
    logradouro: "Sousa Andrade de 141/142 a 609/610",
    bairro: "Brotolandia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-032",
    logradouro: "Valderez Gurgel",
    bairro: "Brotolandia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-022",
    logradouro: "Napoleado Nunes Maia de 122 a 730 lado par",
    bairro: "Brotolandia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-004",
    logradouro: "Padre Vicente de 806 a 1730 lado par",
    bairro: "Brotolandia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-030",
    logradouro: "Francisco Célio de Oliveira Castro até 2298/2299",
    bairro: "Brotolândia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-006",
    logradouro: "Coronel Sindulfo Chaves de 939/940 a 1639/1640",
    bairro: "Brotolândia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-016",
    logradouro: "Joaquim Rodrigues dos Santos de 161/162 a 889/890",
    bairro: "Brotolândia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-670",
    logradouro: "Rua Francisco Carneiro de Araújo de 4108 ao fim - lado par",
    bairro: "Canafístula",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-077",
    logradouro: "Padre Custódio",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-019",
    logradouro: "David Gadelha até 988/989",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-083",
    logradouro: "Avenida dos Expedicionários até 3152/3153",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-055",
    logradouro: "Travessa Felipe Santiago",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-051",
    logradouro: "Felismino Ferreira Maia",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-035",
    logradouro: "Coronel Francisco Remígio até 735 lado impar",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-037",
    logradouro: "Coronel Francisco Remígio até 738 lado par",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-079",
    logradouro: "Travessa Hondrio Nogueira",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-023",
    logradouro: "Travessa larley Leitao",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-021",
    logradouro: "larley Leitéo Caetano",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-095",
    logradouro: "Coronel Inacio Mendes",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-017",
    logradouro: "Coronel Inacio Mendes",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-063",
    logradouro: "Jaime Leonel Chaves até 199/200",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-029",
    logradouro: "Capitão João Eduardo até 1179/1180",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-011",
    logradouro: "João Maria de Freitas lado par ",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-041",
    logradouro: "Padre Joaquim de Menezes",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-097",
    logradouro: "José Agostinho Nogueira",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-067",
    logradouro: "José Jerônimo",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-025",
    logradouro: "Coronel José Nunes lado impar",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-027",
    logradouro: "Coronel José Nunes lado par",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-059",
    logradouro: "Praça José Osterne",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-005",
    logradouro: "José Satino até 299/300",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-057",
    logradouro: "Travessa Lucas Carneiro",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-047",
    logradouro: "Coronel Malveira",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-053",
    logradouro: "Mamede de Oliveira Lima",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-081",
    logradouro: "Manoel Saraiva até 321/322",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-033",
    logradouro: "Travessa Mario Fernandes",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-049",
    logradouro: "Coronel Miguel Vieira de Melo",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-075",
    logradouro: "Patricio Roberto",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-087",
    logradouro: "Raimundo Felipe Neto até 432/433",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-007",
    logradouro: "Travessa Raimundo Fidélis até 1648/1649",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-069",
    logradouro: "Professor Ricarti",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-073",
    logradouro: "Sabino Roberto de Freitas até 3189/3190",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-043",
    logradouro: "Coronel Serafim Chaves até 781 lado impar",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-045",
    logradouro: "Coronel Serafim Chaves até 800 lado par",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-009",
    logradouro: "Coronel Sindulfo Chaves de 1641/1642 ao fim",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-065",
    logradouro: "Coronel José Estácio de 2 ao fim - lado par",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-089",
    logradouro: "Manfredo de Oliveira Lima até 503 lado impar",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-085",
    logradouro: "Cônego  Mizael Alves de Souza lado par",
    bairro: "Centro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-250",
    logradouro: "Avenida do Contorno",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-242",
    logradouro: "Travessa Elizeu Crisdstomo dos Reis",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-236",
    logradouro: "Coronel Francisco Remígio de 1305 ao fim lado impar",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-190",
    logradouro: "Doutor Gaspar de Oliveira de 947 a 1749 lado impar",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-252",
    logradouro: "Hiroshi Gadelha Maia Izidio",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-208",
    logradouro: "João Chagas dos Reis de 1356/1357 ao fim",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-228",
    logradouro: "Capitão João Eduardo de 1721/1722 ao fim",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-196",
    logradouro: "Joao Maria de Freitas",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-226",
    logradouro: "Joaquim Saraiva",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-220",
    logradouro: "José Basilio dos Santos",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-194",
    logradouro: "José Brito Nogueira até 279/280",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-248",
    logradouro: "José Cirineu Maia",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-222",
    logradouro: "Coronel José Nunes lado par",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-200",
    logradouro: "Luiz Vicente Ferreira Lima até 1997/1998",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-198",
    logradouro: "Mixico Nonato",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-240",
    logradouro: "Raimundo Fernandes Feitosa",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-206",
    logradouro: "Padre Santos até 1686/1687",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-204",
    logradouro: "Tenente Sebastião",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-216",
    logradouro: "Vieira de Mello",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-246",
    logradouro: "Zacarias Rodrigues dos Santos",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-214",
    logradouro: "Rosa Gadelha dos Santos de 1376/1377 ao fim",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-212",
    logradouro: "Vilmar Oliveira de Andrade de 1375/1376 ao fim",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-218",
    logradouro: "Jaime Oliveira Lima",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-232",
    logradouro: "João Gomes de Moura",
    bairro: "Doutor José Simões",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-192",
    logradouro: "Francisco de Assis Mendes",
    bairro: "Ilha",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-208",
    logradouro: "Fulgéncio Gomes de Amorim",
    bairro: "Ilha",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-210",
    logradouro: "Joao Gomes de Amorim",
    bairro: "Ilha",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-198",
    logradouro: "José Luiz Gonzaga",
    bairro: "Ilha",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-214",
    logradouro: "José Maria de Sousa",
    bairro: "Ilha",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-206",
    logradouro: "Justino Gomes de Amorim",
    bairro: "Ilha",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-204",
    logradouro: "Laura Paulino de Amorim",
    bairro: "Ilha",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-196",
    logradouro: "Raimundo Gomes de Amorim",
    bairro: "Ilha",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-212",
    logradouro: "Salomao Conrado Maia",
    bairro: "Ilha",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-202",
    logradouro: "Sebastião Neves",
    bairro: "Ilha",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-194",
    logradouro: "Tereza Landim Estacio",
    bairro: "Ilha",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-190",
    logradouro: "Wilson Estacio de Souza",
    bairro: "Ilha",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-146",
    logradouro: "Coronel José Nunes lado impar",
    bairro: "Joao XXIII",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-158",
    logradouro: "Napoledo Nunes Maia até 119/120",
    bairro: "Joao XXIII",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-124",
    logradouro: "Estevao Remigio de Freitas até 738/739",
    bairro: "João XXIII",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-160",
    logradouro: "Francisco Bandeira",
    bairro: "João XXIII",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-132",
    logradouro: "Francisco da Silva Luz",
    bairro: "João XXIII",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-122",
    logradouro: "Coronel Francisco Remígio de 737 a 1303 lado impar",
    bairro: "João XXIII",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-138",
    logradouro: "Doutor Gaspar de Oliveira de 902 a 1750 lado par",
    bairro: "João XXIII",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-142",
    logradouro: "Capitão João Eduardo de 1181/1182 a 1719/1720",
    bairro: "João XXIII",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-152",
    logradouro: "João Maria de Freitas",
    bairro: "João XXIII",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-154",
    logradouro: "João Oliveira Ferreira",
    bairro: "João XXIII",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-130",
    logradouro: "Joaquim Evaristo Gadelha até 2279/2280",
    bairro: "João XXIII",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-134",
    logradouro: "José Lopes Maranhdo até 2298/2299",
    bairro: "João XXIII",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-144",
    logradouro: "Coronel José Nunes lado par",
    bairro: "João XXIII",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-166",
    logradouro: "José Satino de 700/701 ao fim",
    bairro: "João XXIII",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-164",
    logradouro: "Travessa Maria Honorato",
    bairro: "João XXIII",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-148",
    logradouro: "Odilon Felix da Silva",
    bairro: "João XXIII",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-162",
    logradouro: "Sousa Andrade até 139/140",
    bairro: "João XXIII",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-156",
    logradouro: "Padre Vicente de 1127 ao fim lado impar",
    bairro: "João XXIII",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-042",
    logradouro: "David Gadelha de 990/991 ao fim",
    bairro: "Limoeirinho",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-060",
    logradouro: "Edgar Gadelha de Lima",
    bairro: "Limoeirinho",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-062",
    logradouro: "Expedita Barros Silva",
    bairro: "Limoeirinho",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-088",
    logradouro: "Francisca Pereira de Melo",
    bairro: "Limoeirinho",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-082",
    logradouro: "Francisco Augusto de Oliveira",
    bairro: "Limoeirinho",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-044",
    logradouro: "Coronel Inacio Mendes",
    bairro: "Limoeirinho",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-080",
    logradouro: "João Adolfo",
    bairro: "Limoeirinho",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-040",
    logradouro: "Joao Maria de Freitas lado impar ",
    bairro: "Limoeirinho",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-054",
    logradouro: "Joaquim Rodrigues dos Santos até 159/160",
    bairro: "Limoeirinho",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-068",
    logradouro: "José Honorato de Lima",
    bairro: "Limoeirinho",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-056",
    logradouro: "Julio Alves da Silva",
    bairro: "Limoeirinho",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-058",
    logradouro: "Leila Kristinna Lopes Maia",
    bairro: "Limoeirinho",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-084",
    logradouro: "Lili Faheina",
    bairro: "Limoeirinho",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-070",
    logradouro: "Limério Osterne até 1298/1299",
    bairro: "Limoeirinho",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-090",
    logradouro: "Maria lvanir da Silva Lourengo",
    bairro: "Limoeirinho",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-076",
    logradouro: "Maria Lirete Saraiva Feijé",
    bairro: "Limoeirinho",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-086",
    logradouro: "Raimunda Ferreira de Azevedo - Vózinha",
    bairro: "Limoeirinho",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-066",
    logradouro: "Rosa Nunes Vidal",
    bairro: "Limoeirinho",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-074",
    logradouro: "Valderez Gurgel",
    bairro: "Limoeirinho",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62936-046",
    logradouro: "Padre Vicente até 804/805",
    bairro: "Limoeirinho",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-384",
    logradouro: "Francisco Carneiro de Araujo até 99998/99999",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-422",
    logradouro: "Dina Mendes Nunes",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-428",
    logradouro: "Dina Mendes Nunes I",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-458",
    logradouro: "Domingos Evangelista da Silva",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-456",
    logradouro: "Expedito José da Silva",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-432",
    logradouro: "Francisco Assis dos Santos",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-414",
    logradouro: "Travessa Francisco Aureliano de Castro",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-434",
    logradouro: "Travessa Francisco Carneiro de Araujo I",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-406",
    logradouro: "Travessa Francisco Mendes Lima",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-430",
    logradouro: "Francisco Siqueira de Lima",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-398",
    logradouro: "Geraldo Ivo Xavier",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-460",
    logradouro: "Gongalves Pereira",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-382",
    logradouro: "Hermilio Mendes Guerreiro",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-370",
    logradouro: "Hipólito Jerônimo de Oliveira",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-366",
    logradouro: "Travessa Hipólito Jerônimo I",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-368",
    logradouro: "Travessa Hipólito Jerônimo II",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-452",
    logradouro: "Inacio Cosme de Aratijo",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-342",
    logradouro: "Inacio Mendes",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-436",
    logradouro: "João Antonino da Silva",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-328",
    logradouro: "João Lopes de Assis",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-416",
    logradouro: "Travessa Joao Rodrigues de Lima",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-358",
    logradouro: "Joaquim Jaco de Freitas",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-362",
    logradouro: "Travessa Joaquim Lopes",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-364",
    logradouro: "Joaquim Lopes dos Santos",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-350",
    logradouro: "Joaquim Manoel Bessa",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-356",
    logradouro: "José Antônio de Castro",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-404",
    logradouro: "José Augusto da Silva",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-348",
    logradouro: "José Costa Mano",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-410",
    logradouro: "Travessa José da Silva Soares",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-420",
    logradouro: "José de Castro Maia de Freitas até 544/545",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-326",
    logradouro: "José Ferreira Sombra de 2001/2002 ao fim",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-450",
    logradouro: "José Henrique da Silva",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-408",
    logradouro: "Travessa José Nunes",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-440",
    logradouro: "José Roberto Régis até 99999 lado impar av",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-438",
    logradouro: "José Roberto Régis de 2 ao fim lado par av",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-360",
    logradouro: "Ludgero de Sena Lima",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-386",
    logradouro: "Luis Araujo Lima",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-426",
    logradouro: "Luis Ferreira Campos",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-454",
    logradouro: "Margarida Felipe de Oliveira",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-352",
    logradouro: "Maria Carmelita Alves",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-380",
    logradouro: "Maria da Conceigao de Oliveira",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-396",
    logradouro: "Maria Ivo de Freitas",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-402",
    logradouro: "Maria Tercila Nogueira",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-394",
    logradouro: "Maria Vilanir de Freitas",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-424",
    logradouro: "Travessa Marina Mendes",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-418",
    logradouro: "Marina Mendes até 1648/1649",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-372",
    logradouro: "Odete Egidia da Silva",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-388",
    logradouro: "Oliveira Mendes da Silva",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-442",
    logradouro: "Paulino Ferreira Costa",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-446",
    logradouro: "Paulo Roberto Régis",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-336",
    logradouro: "Pedro Coelho até 249/250",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-322",
    logradouro: "Pio Nunes de Andrade",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-344",
    logradouro: "Raimundo Craveiro",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-392",
    logradouro: "Raimundo Ferreira Lopes",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-390",
    logradouro: "Rogério Nogueira da Silva",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-378",
    logradouro: "Terezinha Ivo Xavier",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-354",
    logradouro: "Vital Gomes Ribeiro",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-340",
    logradouro: "Manfredo de Oliveira Lima até 252 lado par",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62930-320",
    logradouro: "Sabino Roberto de Freitas de 3194 ao fim lado par",
    bairro: "Luis Alves Freitas",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-000",
    logradouro: "Coronel José Estácio até 99999 - lado ímpar",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-066",
    logradouro: "Avenida do Contorno",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-022",
    logradouro: "Cremilde Osterne",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-006",
    logradouro: "Estevao Remigio de Freitas de 740/741 a 1395/1396",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-014",
    logradouro: "Francisco Amaro Gomes",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-070",
    logradouro: "Francisco Assis de Lima",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-008",
    logradouro: "Francisco das Chagas Celedénio",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-024",
    logradouro: "Coronel Francisco Remígio de 740 ao fim lado par",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-062",
    logradouro: "Isabel Sousa Bessa - Dona Isabel",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-030",
    logradouro: "Travessa Jaime Leonel",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-012",
    logradouro: "Jaime Leonel Chaves de 201/202 ao fim",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-060",
    logradouro: "Jeova Joaquim de Lima",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-028",
    logradouro: "Joaquim Evaristo Gadelha de 2281/2282 a 2871/2872",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-018",
    logradouro: "Travessa Joaquim Maia",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-050",
    logradouro: "José Felipe Sobrinho",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-002",
    logradouro: "José Hamilton de Oliveira até 159/160",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-072",
    logradouro: "José Joelino Roque",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-032",
    logradouro: "José Lopes Maranhdo de 2300/2301 a 2948/2949",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-056",
    logradouro: "Lauro Rebouças Filho de 1700/1701 ao fim",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-052",
    logradouro: "Maria do Carmo Amorim",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-074",
    logradouro: "Maria Helena Bessa Rodrigues",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-058",
    logradouro: "Raimundo Remigio de Freitas de 1651/1652 ao fim",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-048",
    logradouro: "Travessa Raimundo Remigio II",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-040",
    logradouro: "Tenente Sebastião",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-016",
    logradouro: "Coronel Serafim Chaves de 783/784 ao fim",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-080",
    logradouro: "13 Olga Araujo",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-078",
    logradouro: "14 Olga Araujo",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-076",
    logradouro: "15 Olga Araujo",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-054",
    logradouro: "Luis Gonzaga de Oliveira Osterne lado impar",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-004",
    logradouro: "Manoel Saraiva de 324 ao fim lado par",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-238",
    logradouro: "Rodovia Custódio Saraiva de Menezes de 1500 ao fim - lado par",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-042",
    logradouro:
      "Rodovia Custódio Saraiva de Menezes de 1501 ao fim - lado impar",
    bairro: "Monsenhor Otávio",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-370",
    logradouro: "Avenida do Contorno",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-374",
    logradouro: "Cosme Damião da Silva de 3800/3801 ao fim",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-364",
    logradouro: "Dulcelina Maria de Lima",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-424",
    logradouro: "Edgar Martins Freire",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-376",
    logradouro: "Rua Francisco das Chagas de Moura - Palmeirinha",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-346",
    logradouro: "Francisco das Chagas Leitao",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-356",
    logradouro: "Francisco Pergentino Mendes Guerreiro",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-316",
    logradouro: "Doutor Gaspar de Oliveira até 944/945",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-378",
    logradouro: "Hercilio da Costa e Silva",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-360",
    logradouro: "Idelfonso Solon de Freitas",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-358",
    logradouro: "João Afonso Coelho - Didi Coelho",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-400",
    logradouro: "João Chagas dos Reis até 1354/1355",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-344",
    logradouro: "João Holanda Mendes",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-382",
    logradouro: "Joao Maciel Nogueira",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-368",
    logradouro: "João Marcelino de Sousa",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-352",
    logradouro: "Joaquim Guerreiro Chaves",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-418",
    logradouro: "Joaquim Ricarte de Lima",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-384",
    logradouro: "José Brito Nogueira de 281/282 ao fim",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-348",
    logradouro: "Rua José Carneiro da Silva - Zé Dim",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-336",
    logradouro: "José Firmino dos Santos",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-338",
    logradouro: "Travessa José Firmino dos Santos 02",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-340",
    logradouro: "Travessa José Firmino dos Santos 03",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-342",
    logradouro: "Travessa José Firmino dos Santos 04",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-388",
    logradouro: "José Moreira Chaves - Zé Casinha",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-334",
    logradouro: "José Osete Cruz",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-322",
    logradouro: "Limério Osterne de 1600/1601 ao fim",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-416",
    logradouro: "Luis Mendes Filho",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-408",
    logradouro: "Luiz Vicente Ferreira Lima de 1999/2000 ao fim",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-426",
    logradouro: "Manoel Martins Freire",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-412",
    logradouro: "Maria do Carmo Silva",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-362",
    logradouro: "Professora Maria Luciana Dias",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-420",
    logradouro: "Maria Margarida Nunes Mendes",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-354",
    logradouro: "Mario Guimaraes Peixoto",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-350",
    logradouro: "Professora Neusa Saraiva Chaves",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-386",
    logradouro: "Travessa Novo Habitat",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-380",
    logradouro: "Paulo Alves Filho",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-430",
    logradouro: "Sargento Paulo Sérgio",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-324",
    logradouro: "Raimundo Andrade de Sousa",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-366",
    logradouro: "Raimundo Pereira Lima",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-406",
    logradouro: "Travessa Rosa Gadelha dos Santos",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-404",
    logradouro: "Rosa Gadelha dos Santos até 1618/1619",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-410",
    logradouro: "Padre Santos de 1688/1689 ao fim",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-372",
    logradouro: "Tenente Sebastião",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-422",
    logradouro: "Sérvulo Guimaraes Maia",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-330",
    logradouro: "Travessa Valderez Gurgel",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-328",
    logradouro: "Valderez Gurgel",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-390",
    logradouro: "Vicente Anibal da Silva",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-402",
    logradouro: "Vilmar Oliveira de Andrade até 1373/1374",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-432",
    logradouro: "Corredor de Zé Nilo",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-392",
    logradouro: "Luiz Vicente Ferreira Lima até 498 lado par",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-310",
    logradouro: "Padre Vicente de 1732 ao fim lado par",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-414",
    logradouro: "Vieira de Mello lado par",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-326",
    logradouro: "Napoleão Nunes Maia de 121 a 1399 - lado ímpar",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-314",
    logradouro: "Joaquim Rodrigues dos Santos de 891/892 ao fim",
    bairro: "Pitombeira",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-024",
    logradouro: "Avenida dos Expedicionários de 3154/3155 ao fim",
    bairro: "Santa Luzia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-022",
    logradouro: "Francisco Nunes Guerreiro até 2172 lado par ",
    bairro: "Santa Luzia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-016",
    logradouro: "José Lopes Maranhdo de 2950 a 3450 lado par",
    bairro: "Santa Luzia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-010",
    logradouro: "Manoel Saraiva de 323 a 869 lado impar",
    bairro: "Santa Luzia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-030",
    logradouro: "Sabino Roberto de Freitas de 3191 a 3325 lado impar",
    bairro: "Santa Luzia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-014",
    logradouro: "Joaquim Evaristo Gadelha de 2873/2874 a 3439/3440",
    bairro: "Santa Luzia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-020",
    logradouro: "Francisco Holanda de Oliveira até 737/738",
    bairro: "Santa Luzia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-004",
    logradouro: "José Hamilton de Oliveira de 161/162 a 641/642",
    bairro: "Santa Luzia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-018",
    logradouro: "Manfredo de Oliveira Lima de 254/255 a 983/984",
    bairro: "Santa Luzia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-000",
    logradouro: "Cônego  Mizael Alves de Souza",
    bairro: "Santa Luzia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-032",
    logradouro: "Pedro Coelho de 251/252 ao fim",
    bairro: "Santa Luzia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-006",
    logradouro: "Raimundo Felipe Neto de 434/435 a 998/999",
    bairro: "Santa Luzia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62932-002",
    logradouro: "Raimundo Remigio de Freitas até 679/680",
    bairro: "Santa Luzia",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-630",
    logradouro: "Avenida do Contorno",
    bairro: "Socorro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-556",
    logradouro: "Cosme Damião da Silva até 3588 - lado par",
    bairro: "Socorro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-542",
    logradouro: "Erbas Cavalcante Pinheiro",
    bairro: "Socorro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-548",
    logradouro: "Francisco Augusto de Oliveira",
    bairro: "Socorro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-610",
    logradouro: "Francisco Bandeira",
    bairro: "Socorro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-620",
    logradouro: "Francisco Sabino da Silva",
    bairro: "Socorro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-552",
    logradouro: "João Adolfo",
    bairro: "Socorro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-650",
    logradouro: "José Firmino dos Santos",
    bairro: "Socorro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-550",
    logradouro: "José Osterne Junioaté 848/849",
    bairro: "Socorro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-600",
    logradouro: "Maria de Lourdes Chaves Leitão",
    bairro: "Socorro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-558",
    logradouro: "Nair Holanda Maia",
    bairro: "Socorro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-564",
    logradouro: "Napoleado Nunes Maia de 732/733 ao fim",
    bairro: "Socorro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-546",
    logradouro: "Osvaldo Barros Maia",
    bairro: "Socorro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-544",
    logradouro: "Coronel Sindulfo Chaves até 937/938",
    bairro: "Socorro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62934-560",
    logradouro: "Sousa Andrade de 611/612 ao fim",
    bairro: "Socorro",
    localidade: "",
    uf: "",
    complemento: "",
  },
  {
    cep: "62937-899",
    logradouro: "Zona Rural",
    bairro: "Zona Rural",
    localidade: "",
    uf: "",
    complemento: "",
  },
];
